set -g mouse on
set -g default-shell /usr/bin/fish

# create windows and panes at PWD
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

run-shell ~/.config/tmux/tmux-sensible/sensible.tmux
